"""权限策略引擎门面，老路径兼容垫片。

实现已拆到四个子模块，判定优先级不变。
本文件只做再导出，不放逻辑。
"""

from __future__ import annotations

from .permission_policy import (
    ASK_TOOLS as ASK_TOOLS,
    DANGEROUS_TOOLS as DANGEROUS_TOOLS,
    DEFAULT_COMMAND_RULES as DEFAULT_COMMAND_RULES,
    DEFAULT_TOOL_RULES as DEFAULT_TOOL_RULES,
    DIRECT_MUTATING_TOOLS as DIRECT_MUTATING_TOOLS,
    MUTATING_TOOLS as MUTATING_TOOLS,
    PATH_ARGUMENT_KEYS as PATH_ARGUMENT_KEYS,
    PermissionAction as PermissionAction,
    PermissionDecision as PermissionDecision,
    PermissionPolicy as PermissionPolicy,
    PermissionRequest as PermissionRequest,
    PermissionSource as PermissionSource,
    READ_ONLY_TOOLS as READ_ONLY_TOOLS,
    RESTRICTED_TOOLS as RESTRICTED_TOOLS,
    SAFE_GIT_TOOLS as SAFE_GIT_TOOLS,
    SAFE_WRITE_TOOLS as SAFE_WRITE_TOOLS,
    SOURCE_BUILTIN as SOURCE_BUILTIN,
    SOURCE_PROJECT as SOURCE_PROJECT,
    SOURCE_SESSION as SOURCE_SESSION,
    SOURCE_USER as SOURCE_USER,
    VALID_ACTIONS as VALID_ACTIONS,
    _extract_argument_paths as _extract_argument_paths,
    _is_sensitive_key as _is_sensitive_key,
    _match_rule as _match_rule,
    _match_rule_with_key as _match_rule_with_key,
    _normalize_action as _normalize_action,
    _normalize_path_for_match as _normalize_path_for_match,
    _path_pattern_matches as _path_pattern_matches,
    _policy_paths as _policy_paths,
    _read_policy_file as _read_policy_file,
    summarize_arguments as summarize_arguments,
)
from .permission_session import (
    PermissionRuntime as PermissionRuntime,
    SessionPermissionState as SessionPermissionState,
    _RUNTIME as _RUNTIME,
    _RUNTIME_CONTEXT as _RUNTIME_CONTEXT,
    _SHARED_SESSION_STATE as _SHARED_SESSION_STATE,
    _active_runtime as _active_runtime,
    apply_dangerous_floor as apply_dangerous_floor,
    apply_fallback_decision as apply_fallback_decision,
    build_one_shot_grant as build_one_shot_grant,
    build_parallel_batch_deny as build_parallel_batch_deny,
    consume_one_shot_grant as consume_one_shot_grant,
    is_parallel_batch as is_parallel_batch,
    permission_runtime_session as permission_runtime_session,
)
from .permission_interrupt import (
    _PARALLEL_BATCH as _PARALLEL_BATCH,
    parallel_batch_session as parallel_batch_session,
)
from .permission_workspace import (
    clear_mode_permission_rules as clear_mode_permission_rules,
    configure_permission_workspace as configure_permission_workspace,
    create_permission_runtime as create_permission_runtime,
    enforce_tool_permission as enforce_tool_permission,
    get_permission_audit_log as get_permission_audit_log,
    get_permission_policy_summary as get_permission_policy_summary,
    get_permission_workspace as get_permission_workspace,
    permission_workspace_session as permission_workspace_session,
    reset_session_permission_rules as reset_session_permission_rules,
    restore_permission_workspace as restore_permission_workspace,
    set_mode_permission_rules as set_mode_permission_rules,
    set_permission_confirm_callback as set_permission_confirm_callback,
    set_session_permission_rules as set_session_permission_rules,
    set_tool_permission as set_tool_permission,
    update_session_permission_rules as update_session_permission_rules,
)

__all__ = [
    "DANGEROUS_TOOLS",
    "DEFAULT_COMMAND_RULES",
    "DEFAULT_TOOL_RULES",
    "DIRECT_MUTATING_TOOLS",
    "MUTATING_TOOLS",
    "PATH_ARGUMENT_KEYS",
    "PermissionAction",
    "PermissionDecision",
    "PermissionPolicy",
    "PermissionRequest",
    "PermissionSource",
    "PermissionRuntime",
    "SessionPermissionState",
    "SOURCE_BUILTIN",
    "SOURCE_PROJECT",
    "SOURCE_SESSION",
    "SOURCE_USER",
    "RESTRICTED_TOOLS",
    "READ_ONLY_TOOLS",
    "SAFE_GIT_TOOLS",
    "SAFE_WRITE_TOOLS",
    "VALID_ACTIONS",
    "clear_mode_permission_rules",
    "configure_permission_workspace",
    "create_permission_runtime",
    "enforce_tool_permission",
    "get_permission_audit_log",
    "get_permission_policy_summary",
    "get_permission_workspace",
    "is_parallel_batch",
    "parallel_batch_session",
    "permission_runtime_session",
    "permission_workspace_session",
    "reset_session_permission_rules",
    "restore_permission_workspace",
    "set_mode_permission_rules",
    "set_permission_confirm_callback",
    "set_session_permission_rules",
    "set_tool_permission",
    "summarize_arguments",
    "update_session_permission_rules",
]
